---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: httpd-app
  labels:
    author: intelliqit
spec:
  selector:
    matchLabels:
      author: intelliqit
  template:
    metadata:
      name: http-pod
      labels:
        author: intelliqit
    spec:
      containers:
        - name: myhttpd
          image: httpd
