---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  labels:
    type: cms
spec:
  containers:
    - name: ghost
      image: ghost
  tolerations:
    - key: slave3
      value: intelliqit3
      effect: NoSchedule
      operator: Equal
